apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment
  namespace: default
  labels:
    app: devops 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: devops-demo-new
        image: 23bced29/devops-demo-new:v20250729133830
        ports:
        - containerPort: 80
